### ISSUE TITLE
jQuery version is too old

### ISSUE THREAD

**Issue by phptek** [sheadawson/silverstripe-zenvalidator#74]
Zenvalidator uses a _relatively_ recent version of parsely.js, but in SilverStripe 4 using Firefox v70, it complains that the version of jQuery in use, is too old:

```
12:11:15.160 uncaught exception: The loaded version of jQuery is too old. Please upgrade to 1.8.x or better. main.js:14:2
    <anonymous> main.js:14
    <anonymous> parsley.js:4
    <anonymous> parsley.js:5
```

Looking under my "Network" tab, there are no distinct/separate calls made to "jquery*.js", so I imagine there's a legacy version being included in one of the core bundle.js files, or the jQuery libs that ae based into entwine.js may be the cause of some problem.

A quick solution, might be to bundle a version of jQuery 1.8+ with the module and include via `LeftAndMain::extra_requirements_javascript`.

**Comment by lekoala** [comment]
You mean in the cms? support in the admin is quite difficult. Indeed, SilverStripe include a very old version of jquery because of minor incompatibilities with entwine. this module provide a updated entwine lib. it's not easy to change the version of jquery in the cms.

I would forward the issue to the framework itself
https://github.com/silverstripe/silverstripe-admin/issues/875
https://github.com/silverstripe/silverstripe-framework/issues/3384#issuecomment-490286255
