### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by jinjie** [sheadawson/silverstripe-zenvalidator#76]
On PHP 7.4, which I think the latest SS is now supporting. But saw the following error:
```
PHP Deprecated:  Cannot use "parent" when current class scope has no parent in /redacted..../vendor/sheadawson/silverstripe-zenvalidator/code/ValidationLogicCriteria.php on line 91

Deprecated: Cannot use "parent" when current class scope has no parent in /redacted..../vendor/sheadawson/silverstripe-zenvalidator/code/ValidationLogicCriteria.php on line 91
```

**Comment by lekoala** [comment]
@jinjie yes i got that one too... I'm not sure what's causing this because this is a if block wrapping this call

https://github.com/sheadawson/silverstripe-zenvalidator/blob/ee414173af5a01526cedea3747af2478dddc060f/code/ValidationLogicCriteria.php#L91-L93

if anyone has any idea how to fix this...

**Comment by lekoala** [comment]
this is probably fixed by https://github.com/sheadawson/silverstripe-zenvalidator/commit/5f3f87343072a449201056c974663c30c03cff2a but I haven't a test setup to make sure everything works right. not sure if we need to call $this or $this->parent. Anyway I've referenced the original code from display logic for reference
